apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      # securityContext:
      #   fsGroup: 1000 # user of node group ID
      #   runAsUser: 1000 # user ID
      #   runAsGroup: 1000 # user group ID

      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.0.2

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: mealie-configmap
            # - secretRef:
            #     name: audiobookshelf-container-env

          ports:
            - containerPort: 9000
              protocol: TCP

          volumeMounts:
            - mountPath: "/mealie"
              name: mealie-data-pvc

      restartPolicy: Always

      volumes:
        - name: mealie-data-pvc
          persistentVolumeClaim:
            claimName: mealie-data-pvc
