apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:rfaNsVjXZ8flNYabz5OT71Duh+hxd/faLT6tAqKZEbEV8iTF7t+m0OC7bEsPxUt11kguXicyYkVMGb0m1um3FxJmSNJ0UJtnO6oyFJle/Zbap8K+cvM+UfFvO9red0ozV077NMuqqEbm0gZ9swzVLsQ6WO1LMEOR4hnzP4LNH6y3C+6oEqlu/eXRb8RCXvdkdJKGppCo/oKyhWPJORcVTR/+1xGOcFV2kPjPdI7NXjBoNtnbY7KIbbYbjYAmIuleHqLjvafrMgqCZZLwoz2QaxAZnUiTG/3E,iv:M8zv8xaz555uFCzaK2IfjSwZjvmWT1VhUgAOwvf2JCc=,tag:ADoZt7Rt2HF7YT8rwirX6A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: abs-tunnel-credentials
sops:
    age:
        - recipient: age17n6j3kf05x6jx6dy33xvng947wg0ev8764xrjmcy2akswc0ppd9s8c0jad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNGRFdk1pMjFQbVhMTDlH
            UE5yS1FvcFdZMGdyNUc2bUhFUTlDN0ZIa0RjClY3WFA5aGZoaHk4REw4NFJuYVNo
            Uk9pUFArME5idjNJTUQwWE0vb2RvRWsKLS0tIEtFV29FNTh4K3JheVljdllMeTZI
            VEkzZXh2UnhJdjVCSGR3b0wzR1gxbGcKtzMbAM/+jzVSVqWWrNarUdAU0YQAiUCI
            utj5WI03AXllytVaNRrWuC/b7r2C1G4UtRXIgf7Jv2yGfVR2JmLRiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T23:24:08Z"
    mac: ENC[AES256_GCM,data:g+U23xH9m+m8n/H84Fqs7Eke6FSw2IiQO+tc3clXwUJ0lx6oFP6lQL05QRUaufepN4hLwxs7I6d4nuwdh4x+Q+CJUghBYxruc9DW18RBTtkOPccQJipnUL4lzYN+5grAX6vpdMOpc+bhp2FdPZ2TwutBHM8mdG9rbvESb4PX2bI=,iv:6kW8fX6EFq36x/HqhqwtMxi7kvHIYN+3lPtfPGv++l8=,tag:cj0v0ZtGdeGKMhV196C25Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
