apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf
resources:
  - ../../base/audiobookshelf
  - abs-cloudflare.yaml
  - abs-cloudflare-secret.yaml
  - abs-ingress.yaml
  - audiobookshelf-configmap.yaml
