apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: vaultwarden
resources:
  - ../../base/vaultwarden/
  # - cloudflare.yaml
  # - cloudflare-secret.yaml
  # - vaultwarden-env-secret.yaml
  - ingress.yaml
