apiVersion: v1
kind: Service
metadata:
  name: jenkins-cluster
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /
    prometheus.io/port: "8080"
spec:
  ports:
    - name: httpport
      port: 8080
      targetPort: 8080
    # - name: jenkins-agent
    #   port: 32000
    #   targetPort: 32000
    # - name: jnlpport
    #   port: 50000
    #   targetPort: 50000
  selector:
    app: jenkins-server
  type: ClusterIP
