apiVersion: v1
kind: Service
metadata:
  name: jenkins-cluster
spec:
  ports:
    - name: httpPortA
      port: 8080
      protocol: TCP
    - name: httpPortB
      port: 32000
      protocol: TCP
    - name: httpPortC
      port: 50000
      protocol: TCP
  selector:
    app: jenkins-server
  type: ClusterIP
