apiVersion: v1
kind: Service
metadata:
  name: jenkins-cluster
spec:
  ports:
    - name: http-port-a
      port: 8080
      protocol: TCP
    - name: http-port-b
      port: 32000
      protocol: TCP
    - name: http-port-c
      port: 50000
      protocol: TCP
  selector:
    app: jenkins-server
  type: ClusterIP
