apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        envFrom:
          - configMapRef:
              name: jenkins-configmap
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-data-pvc
          mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data-pvc
          persistentVolumeClaim:
            claimName: jenkins-data-pvc
