apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-tools
resources:
  - deployment.yaml
  - namespace.yaml
  - storage.yaml
  - service.yaml
  - serviceAccount.yaml
  - jenkins-admin-secret.yaml
