---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '3010'
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - port: 3010
      targetPort: 3010
      nodePort: 32000
