apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - name: jenkins-agent
      port: 32000
      targetPort: 32000
      nodePort: 32000
    - name: jnlpport
      port: 50000
      targetPort: 50000
      nodePort: 50000
