apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-tools
  namespace: flux-system
spec:
  interval: 10m0s
  # dependsOn:
  #   - name: infra-configs
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./devops/staging/jenkins
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
