apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  ingressClassName: traefik
  rules:
    - host: jks.nevinlab.com
      http:
        paths:
          - backend:
              service:
                name: jenkins-server
                port:
                  number: 8080
            path: /
            pathType: Prefix
