apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-tools
resources:
  - ../../base/jenkins
  - cloudflare.yaml
  - jenkins-cloudflare-secret.yaml
  - ingress.yaml
  - configmap.yaml
