apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-tools
resources:
  - ../../base/jenkins/
  - jenkins-configmap.yaml
  - cloudflare.yaml
  - ingress.yaml
  - jenkins-cloudflare-secret.yaml
