apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-configmap
  namespace: mealie
data:
  NODE_ENV: "production"
  # CONFIG_PATH: "/config"
  # METADATA_PATH: "/metadata"
  # SOURCE: "docker"
  PORT: "9000"
  USER: "1000:1000"
