apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-configmap
  namespace: renovate
data:
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_GIT_AUTHOR: "David's Renovate Bot <bot@renovateapp.com>"
  RENOVATE_PLATFORM: "github"
  # LOG_LEVEL: "debug"
