apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: renovate-policy
  namespace: renovate
spec:
  podSelector:
    matchLabels:
      app: renovate
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system # Allow ingress from kube-system (for API server communication)
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system # Allow egress to kube-system (for API server communication)
  policyTypes:
  - Ingress
  - Egress
