apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: linkding
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - cnpg-mutating-webhook-configuration.yaml
  - cnpg-validating-webhook-configuration.yaml
  - customresourcedefinition.yaml
